// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx9uK7koSNV3ZzhXmCA4kY-0byhV8Z9Ig',
    appId: '1:449682153173:android:b1c94ef48e43aa86368c5c',
    messagingSenderId: '449682153173',
    projectId: 'warikan-photo',
    storageBucket: 'warikan-photo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDijrsJqRuBuDRBI10Y5hkRwMb9-Qk5Fh8',
    appId: '1:449682153173:ios:5900c98fe97915b2368c5c',
    messagingSenderId: '449682153173',
    projectId: 'warikan-photo',
    storageBucket: 'warikan-photo.appspot.com',
    iosClientId: '449682153173-i2dh5j6m38c7e6bann5bls741nonqna4.apps.googleusercontent.com',
    iosBundleId: 'com.example.warikanPhoto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDijrsJqRuBuDRBI10Y5hkRwMb9-Qk5Fh8',
    appId: '1:449682153173:ios:5900c98fe97915b2368c5c',
    messagingSenderId: '449682153173',
    projectId: 'warikan-photo',
    storageBucket: 'warikan-photo.appspot.com',
    iosClientId: '449682153173-i2dh5j6m38c7e6bann5bls741nonqna4.apps.googleusercontent.com',
    iosBundleId: 'com.example.warikanPhoto',
  );
}
